version: '2'
services:
  db:
    image: mysql:5.7.21
    volumes:
      - /var/lib/docker/volumes/ha_mysql:/var/lib/mysql
    {{- if (.Values.MYSQL_PORT) }}
    ports:
      - ${MYSQL_PORT}:3306
    {{- end }}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  homeassistant:
    depends_on:
      - db
    image: homeassistant/home-assistant:0.61.1
    volumes:
      - /var/lib/docker/volumes/ha_config:/config
    ports:
      - ${HA_PORT}:8123
    devices:
      {{- if (.Values.DEV_ZWAVE) }}
      - ${DEV_ZWAVE}:/zwaveusb:rwm
      {{- end }}
      {{- if (.Values.DEV_RFXCOM) }}
      - ${DEV_RFXCOM}:/rfxtrxusb:rwm
      {{- end }}
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}